### ISSUE TITLE
Dynamic protocol and swap fees

### ISSUE THREAD

**Issue by AugustoL** [levelkdev/dxswap-core#1]
The core smart contracts present two types of fees:

The **swap fee**:
- It is always enabled.
- It is set to be a fixed percentage over the swapped amount in both reserves of 0.3%.
- It goes directly to the liquidity pool.

The **protocol fee**:
- Can be activated at anytime.
- It is set by the `UniswapV2Factory` "owner".
- It is set to be a fixed percentage over the swapped amount in both reserves of 0.05%.
- It is transferred when the liquidity changes via the mint and burn functions exposed by the `UniswapV2Pair` contract.

Proposed changes:
- The `UniswapV2Factory` owner would be able to change the protocol fee receiver and percentage, BUT the percentage has to be equal or lower to 0.05%.
- The `UniswapV2Factory` owner would be able to change the swap fee receiver and percentage for any registered pair, BUT the percentage has to be equal or lower to 0.3%, being 0.01% the minimum percentage allowed to be used.
- The protocol fee will be the same for all pairs and start with 0% as default.
- The swap fee can be different for any pair, but it will start with a default value of 0.3% when a pair is created.
- Have different fees for each pair, each token pair will involve different products and token economics, some of them will be even directly connected within the DXstack of financial services provided by DXdao.

This will allow the DXdao, who will act as `UniswapV2Factory` owner:
- To change the fees within a certain limit, protecting traders and liquidity providers.
- To slowly raise the fee allowing it to receive minimal revenues in an early period and at the same time ensure the liquidity growth.

**Comment by jpkcambridge** [comment]
@AugustoL Nice write up!

One question: Does the protocol fee of 0.05% in Uniswap V2 get taken on BOTH the mint (depositing liquidity) AND burn (withdrawing liquidity), or just on one side?

And some comments on the proposed changes:

- I think the swap fee should be allowed to go higher than 0.3%; I think a range of 0.1%-0.5% could make sense, but I also wonder, is there any reason not to make the range much bigger, like 0-10% for example?

```Have different fees for each pair, each token pair will involve different products and token economics, some of them will be even directly connected within the DXstack of financial services provided by DXdao.
``` . . this is a great point.  And I think it could be a very cool thing to have.  2 concerns come to mind though. . 1) Will this hurt user experience (curious @pimato's thoughts)?  and 2) How much harder will it be to implement, both on the smart contracts and the front end.

**Comment by AugustoL** [comment]
> One question: Does the protocol fee of 0.05% in Uniswap V2 get taken on BOTH the mint (depositing liquidity) AND burn (withdrawing liquidity), or just on one side?

On Both! it is tracked after each swap, but transfered each time the liquidity changes, this saves gas cost on the swap :nerd_face: 

> And some comments on the proposed changes:
> 
> * I think the swap fee should be allowed to go higher than 0.3%; I think a range of 0.1%-0.5% could make sense, but I also wonder, is there any reason not to make the range much bigger, like 0-10% for example?
This fee is payed by the traders ! The higher the fee the less likely is going to be used.
The purpose here is to protect the traders and dapps who will rely on this service to provide always a maximum fee.

> `Have different fees for each pair, each token pair will involve different products and token economics, some of them will be even directly connected within the DXstack of financial services provided by DXdao.`
> . . this is a great point. And I think it could be a very cool thing to have. 2 concerns come to mind though. . 1) Will this hurt user experience (curious @pimato's thoughts)? and 2) How much harder will it be to implement, both on the smart contracts and the front end.

At the beginning not at all! The same values used by uniswap-core will be used by default, and each change will require a DXdao proposal. But in a near future with the next swap-dapp release we can show the fee values for each pair, still a small change.

**Comment by pimato** [comment]
> . . this is a great point. And I think it could be a very cool thing to have. 2 concerns come to mind though. . 1) Will this hurt user experience (curious @pimato's thoughts)? and 2) How much harder will it be to implement, both on the smart contracts and the front end.

I am more concerned about the changes we are going to introduce compared to the UX challenges. Adding a fee indicator once we have fee will be no issue!

**Comment by AugustoL** [comment]
> > . . this is a great point. And I think it could be a very cool thing to have. 2 concerns come to mind though. . 1) Will this hurt user experience (curious @pimato's thoughts)? and 2) How much harder will it be to implement, both on the smart contracts and the front end.
> 
> I am more concerned about the changes we are going to introduce in terms of security risks compared to the UX challenges. Adding a fee indicator once we have fee will be no issue!

The changes to be introduced will only impact the values used for the fee calculation. We just need to make sure which address has the right to set it, and to check that the new fees sets are valid.

The requirements would be:
- Replace the fees in the fees calculation with values obtained from the factory contract.
- Add the setters for each fee in the factory contract.
- Used the 0.05% protocol fee and 0.3% swap fee as default.
- Dont apply any change, and remove any of the tests cases already implemented.
- Add tests cases to check the new values of the fees, and verify the right balance of the reserves after each operation.

@jpkcambridge @pimato what do you think?

**Comment by pimato** [comment]
I think it is great! Lets do it @AugustoL

**Comment by KadenZipfel** [comment]
> * I think the swap fee should be allowed to go higher than 0.3%; I think a range of 0.1%-0.5% could make sense, but I also wonder, is there any reason not to make the range much bigger, like 0-10% for example?

I agree that a range of 0.1%-0.5% might be reasonable, but I think beyond a certain maximum range, we can see UX issues if users go through with a trade without noticing the swap fee. Though, perhaps to combat this we could have a warning for any trade with a swap fee above a certain amount, say 0.3%, but this of course is only a solution for use on the interface and not manual use. I can see this being problematic if the trade is being performed by a dex aggregator for example.

**Comment by jpkcambridge** [comment]
> > * I think the swap fee should be allowed to go higher than 0.3%; I think a range of 0.1%-0.5% could make sense, but I also wonder, is there any reason not to make the range much bigger, like 0-10% for example?
> 
> I agree that a range of 0.1%-0.5% might be reasonable, but I think beyond a certain maximum range, we can see UX issues if users go through with a trade without noticing the swap fee. Though, perhaps to combat this we could have a warning for any trade with a swap fee above a certain amount, say 0.3%, but this of course is only a solution for use on the interface and not manual use. I can see this being problematic if the trade is being performed by a dex aggregator for example.

I am not sure that would be a problem with dex aggregators, since aggregators are trying to find the best prices.  I suppose it could increase the risk a dex aggregator does some calculations wrong depending on how they make the integration.
