### ISSUE TITLE
Smart contract names

### ISSUE THREAD

**Issue by AugustoL** [levelkdev/dxswap-core#2]
Currently the naming in the contracts are all "uniswap" related. 

It will be confusing to for dapps in the DXsatck to use functions in dapps with a name completely unrelated to it.

We have **two options**: A **general name** that can be used and forked, like TokenPair, TokenPairFactory, TokenSwap, OR a **name that refers to the DXswap** app, like DXSwapPair, DXSwapTokenPairFatcory, DXTokenSwap or something similar.

I think that even though this contracts would be used for DXswap, it would be much better to have general names that dont relate the contracts to the project that developed it or use it, for the sake of more open-source and having more forkable code (?

**Comment by AugustoL** [comment]
@jpkcambridge @pimato thoughts?

**Comment by nicoelzer** [comment]
@AugustoL like the option to keep the names generic.

**Comment by jpkcambridge** [comment]
@AugustoL I am also in favor of generic names and making it easier to fork.
